spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  security: 
    oauth2:
      client:
        registration:
          facebook:
              clientId: 3215451234
              clientSecret: 123551432
              scope: email, public_profle

logging:
  level:
    tacos: DEBUG
    
taco:
  orders:
    pageSize: 10

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN