spring:
    datasource:
        generate-unique-name: false
        name: tacocloud
    security: 
      oauth2:
        client:
          registration:
            facebook:
                clientId: 3215451234
                clientSecret: 123551432
                scope: email, public_profle